///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Hoclieu6
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Hoclieu6Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("db39e013-f199-490f-a49b-b3cef3bdb189")]
    public partial class Hoclieu6Repository : RepoGenBaseFolder
    {
        static Hoclieu6Repository instance = new Hoclieu6Repository();
        Hoclieu6RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        Hoclieu6RepositoryFolders.ĐăngNhậpSachMềmAppFolder _đăngnhậpsachmềm;
        Hoclieu6RepositoryFolders.HọcLiệuSachMềmGoogleChromeAppFolder _họcliệusachmềmgooglechrome;

        /// <summary>
        /// Gets the singleton class instance representing the Hoclieu6Repository element repository.
        /// </summary>
        [RepositoryFolder("db39e013-f199-490f-a49b-b3cef3bdb189")]
        public static Hoclieu6Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Hoclieu6Repository() 
            : base("Hoclieu6Repository", "/", null, 0, false, "db39e013-f199-490f-a49b-b3cef3bdb189", ".\\RepositoryImages\\Hoclieu6Repositorydb39e013.rximgres")
        {
            _applicationundertest = new Hoclieu6RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _đăngnhậpsachmềm = new Hoclieu6RepositoryFolders.ĐăngNhậpSachMềmAppFolder(this);
            _họcliệusachmềmgooglechrome = new Hoclieu6RepositoryFolders.HọcLiệuSachMềmGoogleChromeAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("db39e013-f199-490f-a49b-b3cef3bdb189")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("42d9e791-a556-497f-b4cd-361fac2d932f")]
        public virtual Hoclieu6RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The ĐăngNhậpSachMềm folder.
        /// </summary>
        [RepositoryFolder("107f076c-3feb-46b6-b887-c25fa04b18fa")]
        public virtual Hoclieu6RepositoryFolders.ĐăngNhậpSachMềmAppFolder ĐăngNhậpSachMềm
        {
            get { return _đăngnhậpsachmềm; }
        }

        /// <summary>
        /// The HọcLiệuSachMềmGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("362a6b60-b566-4e0f-9a1b-94528ba256b9")]
        public virtual Hoclieu6RepositoryFolders.HọcLiệuSachMềmGoogleChromeAppFolder HọcLiệuSachMềmGoogleChrome
        {
            get { return _họcliệusachmềmgooglechrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Hoclieu6RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("42d9e791-a556-497f-b4cd-361fac2d932f")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            Hoclieu6RepositoryFolders.ContainerFolder _container;
            RepoItemInfo _optiondropdownInfo;
            RepoItemInfo _atagchỉnhsửaInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _divtagthanhcongInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='hoclieu.sachmem.vn']", parentFolder, 30000, null, false, "42d9e791-a556-497f-b4cd-361fac2d932f", "")
            {
                _container = new Hoclieu6RepositoryFolders.ContainerFolder(this);
                _optiondropdownInfo = new RepoItemInfo(this, "OptionDropdown", ".//div[#'scroll-question']//ul/li[1]/div/div[2]/?/?/a[@id='optionDropdown']", 30000, null, "c291523c-1769-4441-a0cc-b1684ba8b05f");
                _atagchỉnhsửaInfo = new RepoItemInfo(this, "ATagChỉnhSửa", ".//div[#'scroll-question']//ul/li[1]/div/div[2]/span[2]/?/?/a[@innertext=' Chỉnh sửa            ']", 30000, null, "5c188003-8dd4-400b-9036-d6294dac2b00");
                _textInfo = new RepoItemInfo(this, "Text", ".//div[#'editAssignmentModal']//form[@action='https://hoclieu.sachmem.vn/live_class/class/5c6d0af10966f254d79b604d/assignments']/div[1]/div[1]/input[@type='text']", 30000, null, "fe07d3fb-913f-4d2d-9186-ddea1e5b5ed4");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//div[#'editAssignmentModal']//form[@action='https://hoclieu.sachmem.vn/live_class/class/5c6d0af10966f254d79b604d/assignments']/?/?/input[@type='submit']", 30000, null, "8774add3-bed1-48e8-9b3b-a57813297e1c");
                _divtagthanhcongInfo = new RepoItemInfo(this, "DivTagThanhCong", ".//div[#'toast-container']/?/?/div[@innertext=' Thành công! ']", 30000, null, "fe1704a5-39cb-4cdf-9f67-831304425e74");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("42d9e791-a556-497f-b4cd-361fac2d932f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("42d9e791-a556-497f-b4cd-361fac2d932f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OptionDropdown item.
            /// </summary>
            [RepositoryItem("c291523c-1769-4441-a0cc-b1684ba8b05f")]
            public virtual Ranorex.ATag OptionDropdown
            {
                get
                {
                    return _optiondropdownInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The OptionDropdown item info.
            /// </summary>
            [RepositoryItemInfo("c291523c-1769-4441-a0cc-b1684ba8b05f")]
            public virtual RepoItemInfo OptionDropdownInfo
            {
                get
                {
                    return _optiondropdownInfo;
                }
            }

            /// <summary>
            /// The ATagChỉnhSửa item.
            /// </summary>
            [RepositoryItem("5c188003-8dd4-400b-9036-d6294dac2b00")]
            public virtual Ranorex.ATag ATagChỉnhSửa
            {
                get
                {
                    return _atagchỉnhsửaInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagChỉnhSửa item info.
            /// </summary>
            [RepositoryItemInfo("5c188003-8dd4-400b-9036-d6294dac2b00")]
            public virtual RepoItemInfo ATagChỉnhSửaInfo
            {
                get
                {
                    return _atagchỉnhsửaInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("fe07d3fb-913f-4d2d-9186-ddea1e5b5ed4")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("fe07d3fb-913f-4d2d-9186-ddea1e5b5ed4")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("8774add3-bed1-48e8-9b3b-a57813297e1c")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("8774add3-bed1-48e8-9b3b-a57813297e1c")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The DivTagThanhCong item.
            /// </summary>
            [RepositoryItem("fe1704a5-39cb-4cdf-9f67-831304425e74")]
            public virtual Ranorex.DivTag DivTagThanhCong
            {
                get
                {
                    return _divtagthanhcongInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagThanhCong item info.
            /// </summary>
            [RepositoryItemInfo("fe1704a5-39cb-4cdf-9f67-831304425e74")]
            public virtual RepoItemInfo DivTagThanhCongInfo
            {
                get
                {
                    return _divtagthanhcongInfo;
                }
            }

            /// <summary>
            /// The Container folder.
            /// </summary>
            [RepositoryFolder("6916451f-0fd1-4d4a-bbf7-e1babb094d60")]
            public virtual Hoclieu6RepositoryFolders.ContainerFolder Container
            {
                get { return _container; }
            }
        }

        /// <summary>
        /// The ContainerFolder folder.
        /// </summary>
        [RepositoryFolder("6916451f-0fd1-4d4a-bbf7-e1babb094d60")]
        public partial class ContainerFolder : RepoGenBaseFolder
        {
            RepoItemInfo _đăngnhậpInfo;
            RepoItemInfo _lớplớpInfo;
            RepoItemInfo _lớphọccủatoiInfo;

            /// <summary>
            /// Creates a new Container  folder.
            /// </summary>
            public ContainerFolder(RepoGenBaseFolder parentFolder) :
                    base("Container", "body/tag[@tagname='app-root']/div[2]/div", parentFolder, 30000, null, false, "6916451f-0fd1-4d4a-bbf7-e1babb094d60", "")
            {
                _đăngnhậpInfo = new RepoItemInfo(this, "ĐăngNhập", ".//div[@innertext~'^\\ \\ Để\\ sử\\ dụng\\ bạn\\ cần\\ \\ ho']/a[@innertext='Đăng nhập']", 30000, null, "0c7ec214-783b-4497-9247-8cdc2c766ad6");
                _lớplớpInfo = new RepoItemInfo(this, "LớpLớp", ".//tag[@tagname='app-list-class']/ul[1]/li/div/div[1]/a[@innertext='Lớp lớp']", 30000, null, "0ddfd0e2-72ad-4b7c-a6e8-45b82ec18bcc");
                _lớphọccủatoiInfo = new RepoItemInfo(this, "LớpHọcCủaToi", "div//ul/li[1]//a[@innertext='Lớp học của tôi']", 30000, null, "ceef241d-ac70-437e-aaf1-93cd868b19dd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6916451f-0fd1-4d4a-bbf7-e1babb094d60")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6916451f-0fd1-4d4a-bbf7-e1babb094d60")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ĐăngNhập item.
            /// </summary>
            [RepositoryItem("0c7ec214-783b-4497-9247-8cdc2c766ad6")]
            public virtual Ranorex.ATag ĐăngNhập
            {
                get
                {
                    return _đăngnhậpInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ĐăngNhập item info.
            /// </summary>
            [RepositoryItemInfo("0c7ec214-783b-4497-9247-8cdc2c766ad6")]
            public virtual RepoItemInfo ĐăngNhậpInfo
            {
                get
                {
                    return _đăngnhậpInfo;
                }
            }

            /// <summary>
            /// The LớpLớp item.
            /// </summary>
            [RepositoryItem("0ddfd0e2-72ad-4b7c-a6e8-45b82ec18bcc")]
            public virtual Ranorex.ATag LớpLớp
            {
                get
                {
                    return _lớplớpInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LớpLớp item info.
            /// </summary>
            [RepositoryItemInfo("0ddfd0e2-72ad-4b7c-a6e8-45b82ec18bcc")]
            public virtual RepoItemInfo LớpLớpInfo
            {
                get
                {
                    return _lớplớpInfo;
                }
            }

            /// <summary>
            /// The LớpHọcCủaToi item.
            /// </summary>
            [RepositoryItem("ceef241d-ac70-437e-aaf1-93cd868b19dd")]
            public virtual Ranorex.ATag LớpHọcCủaToi
            {
                get
                {
                    return _lớphọccủatoiInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LớpHọcCủaToi item info.
            /// </summary>
            [RepositoryItemInfo("ceef241d-ac70-437e-aaf1-93cd868b19dd")]
            public virtual RepoItemInfo LớpHọcCủaToiInfo
            {
                get
                {
                    return _lớphọccủatoiInfo;
                }
            }
        }

        /// <summary>
        /// The ĐăngNhậpSachMềmAppFolder folder.
        /// </summary>
        [RepositoryFolder("107f076c-3feb-46b6-b887-c25fa04b18fa")]
        public partial class ĐăngNhậpSachMềmAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _commitInfo;

            /// <summary>
            /// Creates a new ĐăngNhậpSachMềm  folder.
            /// </summary>
            public ĐăngNhậpSachMềmAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ĐăngNhậpSachMềm", "/dom[@domain='accounts.sachmem.vn']", parentFolder, 30000, null, false, "107f076c-3feb-46b6-b887-c25fa04b18fa", "")
            {
                _commitInfo = new RepoItemInfo(this, "Commit", ".//form[#'new_user']/?/?/input[@name='commit']", 30000, null, "5b2ab1bc-b41e-4969-a525-f4904ab71cc0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("107f076c-3feb-46b6-b887-c25fa04b18fa")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("107f076c-3feb-46b6-b887-c25fa04b18fa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Commit item.
            /// </summary>
            [RepositoryItem("5b2ab1bc-b41e-4969-a525-f4904ab71cc0")]
            public virtual Ranorex.InputTag Commit
            {
                get
                {
                    return _commitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Commit item info.
            /// </summary>
            [RepositoryItemInfo("5b2ab1bc-b41e-4969-a525-f4904ab71cc0")]
            public virtual RepoItemInfo CommitInfo
            {
                get
                {
                    return _commitInfo;
                }
            }
        }

        /// <summary>
        /// The HọcLiệuSachMềmGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("362a6b60-b566-4e0f-9a1b-94528ba256b9")]
        public partial class HọcLiệuSachMềmGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _motmi98testingInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _họcliệusachmềmInfo;

            /// <summary>
            /// Creates a new HọcLiệuSachMềmGoogleChrome  folder.
            /// </summary>
            public HọcLiệuSachMềmGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HọcLiệuSachMềmGoogleChrome", "/form[@title~'^Học\\ liệu\\ -\\ Sách\\ Mềm\\ -\\ Goo']", parentFolder, 30000, null, true, "362a6b60-b566-4e0f-9a1b-94528ba256b9", "")
            {
                _motmi98testingInfo = new RepoItemInfo(this, "Motmi98Testing", "container[@accessiblename~'^Học\\ liệu\\ -\\ Sách\\ Mềm\\ -\\ Goo']/container[@accessiblename='Google Chrome']//tabpage[@accessiblename='motmi98/Testing']", 30000, null, "dabbf974-571b-4e0a-b82b-20da7fa4f5cf");
                _closeInfo = new RepoItemInfo(this, "Close", "container[@accessiblename~'^Học\\ liệu\\ -\\ Sách\\ Mềm\\ -\\ Goo']/container[@accessiblename='Google Chrome']//tabpage[@accessiblerole='PageTab' and @title='Học liệu - Sách Mềm' and @index='4']/button[@accessiblename='Close']", 30000, null, "46847a5d-2a29-4f76-b6c4-0a7ea454d559");
                _họcliệusachmềmInfo = new RepoItemInfo(this, "HọcLiệuSachMềm", "container[@accessiblename~'^motmi98/Testing\\ -\\ Google\\ ']/container[@accessiblename='Google Chrome']//tabpage[@accessiblename='Học liệu - Sách Mềm']", 30000, null, "caf4fdb5-0b2e-4815-a0f8-acc3a05038da");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("362a6b60-b566-4e0f-9a1b-94528ba256b9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("362a6b60-b566-4e0f-9a1b-94528ba256b9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Motmi98Testing item.
            /// </summary>
            [RepositoryItem("dabbf974-571b-4e0a-b82b-20da7fa4f5cf")]
            public virtual Ranorex.TabPage Motmi98Testing
            {
                get
                {
                    return _motmi98testingInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Motmi98Testing item info.
            /// </summary>
            [RepositoryItemInfo("dabbf974-571b-4e0a-b82b-20da7fa4f5cf")]
            public virtual RepoItemInfo Motmi98TestingInfo
            {
                get
                {
                    return _motmi98testingInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("46847a5d-2a29-4f76-b6c4-0a7ea454d559")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("46847a5d-2a29-4f76-b6c4-0a7ea454d559")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The HọcLiệuSachMềm item.
            /// </summary>
            [RepositoryItem("caf4fdb5-0b2e-4815-a0f8-acc3a05038da")]
            public virtual Ranorex.TabPage HọcLiệuSachMềm
            {
                get
                {
                    return _họcliệusachmềmInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The HọcLiệuSachMềm item info.
            /// </summary>
            [RepositoryItemInfo("caf4fdb5-0b2e-4815-a0f8-acc3a05038da")]
            public virtual RepoItemInfo HọcLiệuSachMềmInfo
            {
                get
                {
                    return _họcliệusachmềmInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
