///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Hoclieu7
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Hoclieu7Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("3154f3d2-5f4d-4739-90e1-060a6442c249")]
    public partial class Hoclieu7Repository : RepoGenBaseFolder
    {
        static Hoclieu7Repository instance = new Hoclieu7Repository();
        Hoclieu7RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        Hoclieu7RepositoryFolders.ĐăngNhậpSachMềmAppFolder _đăngnhậpsachmềm;
        Hoclieu7RepositoryFolders.HọcLiệuSachMềmGoogleChromeAppFolder _họcliệusachmềmgooglechrome;

        /// <summary>
        /// Gets the singleton class instance representing the Hoclieu7Repository element repository.
        /// </summary>
        [RepositoryFolder("3154f3d2-5f4d-4739-90e1-060a6442c249")]
        public static Hoclieu7Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Hoclieu7Repository() 
            : base("Hoclieu7Repository", "/", null, 0, false, "3154f3d2-5f4d-4739-90e1-060a6442c249", ".\\RepositoryImages\\Hoclieu7Repository3154f3d2.rximgres")
        {
            _applicationundertest = new Hoclieu7RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _đăngnhậpsachmềm = new Hoclieu7RepositoryFolders.ĐăngNhậpSachMềmAppFolder(this);
            _họcliệusachmềmgooglechrome = new Hoclieu7RepositoryFolders.HọcLiệuSachMềmGoogleChromeAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3154f3d2-5f4d-4739-90e1-060a6442c249")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("a5ff55b4-db5f-478a-bf5b-9c44847f6024")]
        public virtual Hoclieu7RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The ĐăngNhậpSachMềm folder.
        /// </summary>
        [RepositoryFolder("f1323612-d2d1-4c77-a5cf-514ae9e96efc")]
        public virtual Hoclieu7RepositoryFolders.ĐăngNhậpSachMềmAppFolder ĐăngNhậpSachMềm
        {
            get { return _đăngnhậpsachmềm; }
        }

        /// <summary>
        /// The HọcLiệuSachMềmGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("bc576f29-800d-4aab-b914-a7fe969a932f")]
        public virtual Hoclieu7RepositoryFolders.HọcLiệuSachMềmGoogleChromeAppFolder HọcLiệuSachMềmGoogleChrome
        {
            get { return _họcliệusachmềmgooglechrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Hoclieu7RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("a5ff55b4-db5f-478a-bf5b-9c44847f6024")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            Hoclieu7RepositoryFolders.ContainerFolder _container;
            RepoItemInfo _phanhieuInfo;
            RepoItemInfo _gửitinnhắnInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='hoclieu.sachmem.vn']", parentFolder, 30000, null, false, "a5ff55b4-db5f-478a-bf5b-9c44847f6024", "")
            {
                _container = new Hoclieu7RepositoryFolders.ContainerFolder(this);
                _phanhieuInfo = new RepoItemInfo(this, "PhanHieu", ".//div[#'sidebar-wrapper']/div[3]//p[@innertext='Phan Hieu']", 30000, null, "bef670a1-42ff-4417-83fa-b2d0d93f67b2");
                _gửitinnhắnInfo = new RepoItemInfo(this, "GửiTinNhắn", ".//div[#'page-content-wrapper']//textarea[@placeholder='Gửi tin nhắn']", 30000, null, "bc332dd2-12b8-438b-adc6-72a8d46a470b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a5ff55b4-db5f-478a-bf5b-9c44847f6024")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a5ff55b4-db5f-478a-bf5b-9c44847f6024")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PhanHieu item.
            /// </summary>
            [RepositoryItem("bef670a1-42ff-4417-83fa-b2d0d93f67b2")]
            public virtual Ranorex.PTag PhanHieu
            {
                get
                {
                    return _phanhieuInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The PhanHieu item info.
            /// </summary>
            [RepositoryItemInfo("bef670a1-42ff-4417-83fa-b2d0d93f67b2")]
            public virtual RepoItemInfo PhanHieuInfo
            {
                get
                {
                    return _phanhieuInfo;
                }
            }

            /// <summary>
            /// The GửiTinNhắn item.
            /// </summary>
            [RepositoryItem("bc332dd2-12b8-438b-adc6-72a8d46a470b")]
            public virtual Ranorex.TextAreaTag GửiTinNhắn
            {
                get
                {
                    return _gửitinnhắnInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The GửiTinNhắn item info.
            /// </summary>
            [RepositoryItemInfo("bc332dd2-12b8-438b-adc6-72a8d46a470b")]
            public virtual RepoItemInfo GửiTinNhắnInfo
            {
                get
                {
                    return _gửitinnhắnInfo;
                }
            }

            /// <summary>
            /// The Container folder.
            /// </summary>
            [RepositoryFolder("00bcfaff-79c5-4c29-b43e-e01907e07e8e")]
            public virtual Hoclieu7RepositoryFolders.ContainerFolder Container
            {
                get { return _container; }
            }
        }

        /// <summary>
        /// The ContainerFolder folder.
        /// </summary>
        [RepositoryFolder("00bcfaff-79c5-4c29-b43e-e01907e07e8e")]
        public partial class ContainerFolder : RepoGenBaseFolder
        {
            RepoItemInfo _đăngnhậpInfo;
            RepoItemInfo _divtagnhắntintraođổiInfo;
            RepoItemInfo _lớplớpInfo;
            RepoItemInfo _lớphọccủatoiInfo;
            RepoItemInfo _fafapaperplaneInfo;
            RepoItemInfo _spantagathashdollarpercentcaretInfo;

            /// <summary>
            /// Creates a new Container  folder.
            /// </summary>
            public ContainerFolder(RepoGenBaseFolder parentFolder) :
                    base("Container", "body/tag[@tagname='app-root']/div[2]/div", parentFolder, 30000, null, false, "00bcfaff-79c5-4c29-b43e-e01907e07e8e", "")
            {
                _đăngnhậpInfo = new RepoItemInfo(this, "ĐăngNhập", ".//div[@innertext~'^\\ \\ Để\\ sử\\ dụng\\ bạn\\ cần\\ \\ ho']/a[@innertext='Đăng nhập']", 30000, null, "6cb2a0e7-44d1-4a36-a455-cd9b32767ca9");
                _divtagnhắntintraođổiInfo = new RepoItemInfo(this, "DivTagNhắnTinTraoĐổi", ".//tag[@tagname='app-action']/div/div[1]/div[@innertext=' Nhắn tin, trao đổi    ']", 30000, null, "bbff40a6-6aae-41c3-afc8-1c9a0aae97b0");
                _lớplớpInfo = new RepoItemInfo(this, "LớpLớp", ".//tag[@tagname='app-list-class']/ul[1]/li/div/div[1]/a[@innertext='Lớp lớp']", 30000, null, "25bcff73-1771-4df2-b458-176fac108d59");
                _lớphọccủatoiInfo = new RepoItemInfo(this, "LớpHọcCủaToi", "div//ul/li[1]//a[@innertext='Lớp học của tôi']", 30000, null, "f5fbd40a-7fcf-4c5e-9002-5d92bc2e162f");
                _fafapaperplaneInfo = new RepoItemInfo(this, "FaFaPaperPlane", ".//button[@innertext=' Gửi              ']/i", 30000, null, "4aacc462-9a2d-4353-ae86-13deba1d54f4");
                _spantagathashdollarpercentcaretInfo = new RepoItemInfo(this, "SpanTagAtHashDollarPercentCaret", "div//span[@innertext='!@#$%^&']", 30000, null, "cc8460ee-8338-466e-8a84-8226e681af54");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("00bcfaff-79c5-4c29-b43e-e01907e07e8e")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("00bcfaff-79c5-4c29-b43e-e01907e07e8e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ĐăngNhập item.
            /// </summary>
            [RepositoryItem("6cb2a0e7-44d1-4a36-a455-cd9b32767ca9")]
            public virtual Ranorex.ATag ĐăngNhập
            {
                get
                {
                    return _đăngnhậpInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ĐăngNhập item info.
            /// </summary>
            [RepositoryItemInfo("6cb2a0e7-44d1-4a36-a455-cd9b32767ca9")]
            public virtual RepoItemInfo ĐăngNhậpInfo
            {
                get
                {
                    return _đăngnhậpInfo;
                }
            }

            /// <summary>
            /// The DivTagNhắnTinTraoĐổi item.
            /// </summary>
            [RepositoryItem("bbff40a6-6aae-41c3-afc8-1c9a0aae97b0")]
            public virtual Ranorex.DivTag DivTagNhắnTinTraoĐổi
            {
                get
                {
                    return _divtagnhắntintraođổiInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagNhắnTinTraoĐổi item info.
            /// </summary>
            [RepositoryItemInfo("bbff40a6-6aae-41c3-afc8-1c9a0aae97b0")]
            public virtual RepoItemInfo DivTagNhắnTinTraoĐổiInfo
            {
                get
                {
                    return _divtagnhắntintraođổiInfo;
                }
            }

            /// <summary>
            /// The LớpLớp item.
            /// </summary>
            [RepositoryItem("25bcff73-1771-4df2-b458-176fac108d59")]
            public virtual Ranorex.ATag LớpLớp
            {
                get
                {
                    return _lớplớpInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LớpLớp item info.
            /// </summary>
            [RepositoryItemInfo("25bcff73-1771-4df2-b458-176fac108d59")]
            public virtual RepoItemInfo LớpLớpInfo
            {
                get
                {
                    return _lớplớpInfo;
                }
            }

            /// <summary>
            /// The LớpHọcCủaToi item.
            /// </summary>
            [RepositoryItem("f5fbd40a-7fcf-4c5e-9002-5d92bc2e162f")]
            public virtual Ranorex.ATag LớpHọcCủaToi
            {
                get
                {
                    return _lớphọccủatoiInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LớpHọcCủaToi item info.
            /// </summary>
            [RepositoryItemInfo("f5fbd40a-7fcf-4c5e-9002-5d92bc2e162f")]
            public virtual RepoItemInfo LớpHọcCủaToiInfo
            {
                get
                {
                    return _lớphọccủatoiInfo;
                }
            }

            /// <summary>
            /// The FaFaPaperPlane item.
            /// </summary>
            [RepositoryItem("4aacc462-9a2d-4353-ae86-13deba1d54f4")]
            public virtual Ranorex.ITag FaFaPaperPlane
            {
                get
                {
                    return _fafapaperplaneInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FaFaPaperPlane item info.
            /// </summary>
            [RepositoryItemInfo("4aacc462-9a2d-4353-ae86-13deba1d54f4")]
            public virtual RepoItemInfo FaFaPaperPlaneInfo
            {
                get
                {
                    return _fafapaperplaneInfo;
                }
            }

            /// <summary>
            /// The SpanTagAtHashDollarPercentCaret item.
            /// </summary>
            [RepositoryItem("cc8460ee-8338-466e-8a84-8226e681af54")]
            public virtual Ranorex.SpanTag SpanTagAtHashDollarPercentCaret
            {
                get
                {
                    return _spantagathashdollarpercentcaretInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagAtHashDollarPercentCaret item info.
            /// </summary>
            [RepositoryItemInfo("cc8460ee-8338-466e-8a84-8226e681af54")]
            public virtual RepoItemInfo SpanTagAtHashDollarPercentCaretInfo
            {
                get
                {
                    return _spantagathashdollarpercentcaretInfo;
                }
            }
        }

        /// <summary>
        /// The ĐăngNhậpSachMềmAppFolder folder.
        /// </summary>
        [RepositoryFolder("f1323612-d2d1-4c77-a5cf-514ae9e96efc")]
        public partial class ĐăngNhậpSachMềmAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _commitInfo;

            /// <summary>
            /// Creates a new ĐăngNhậpSachMềm  folder.
            /// </summary>
            public ĐăngNhậpSachMềmAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ĐăngNhậpSachMềm", "/dom[@domain='accounts.sachmem.vn']", parentFolder, 30000, null, false, "f1323612-d2d1-4c77-a5cf-514ae9e96efc", "")
            {
                _commitInfo = new RepoItemInfo(this, "Commit", ".//form[#'new_user']/?/?/input[@name='commit']", 30000, null, "e4476890-5d24-4b35-9ca3-0d495f442026");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f1323612-d2d1-4c77-a5cf-514ae9e96efc")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f1323612-d2d1-4c77-a5cf-514ae9e96efc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Commit item.
            /// </summary>
            [RepositoryItem("e4476890-5d24-4b35-9ca3-0d495f442026")]
            public virtual Ranorex.InputTag Commit
            {
                get
                {
                    return _commitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Commit item info.
            /// </summary>
            [RepositoryItemInfo("e4476890-5d24-4b35-9ca3-0d495f442026")]
            public virtual RepoItemInfo CommitInfo
            {
                get
                {
                    return _commitInfo;
                }
            }
        }

        /// <summary>
        /// The HọcLiệuSachMềmGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("bc576f29-800d-4aab-b914-a7fe969a932f")]
        public partial class HọcLiệuSachMềmGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _baitậpthựchanhkiểmthửmonint31172Info;

            /// <summary>
            /// Creates a new HọcLiệuSachMềmGoogleChrome  folder.
            /// </summary>
            public HọcLiệuSachMềmGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HọcLiệuSachMềmGoogleChrome", "/form[@title~'^Học\\ liệu\\ -\\ Sách\\ Mềm\\ -\\ Goo']", parentFolder, 30000, null, true, "bc576f29-800d-4aab-b914-a7fe969a932f", "")
            {
                _baitậpthựchanhkiểmthửmonint31172Info = new RepoItemInfo(this, "BaiTậpThựcHanhKiểmThửMonINT31172", "container[@accessiblename~'^Học\\ liệu\\ -\\ Sách\\ Mềm\\ -\\ Goo']/container[@accessiblename='Google Chrome']//tabpage[@accessiblename~'^Bài\\ tập\\ thực\\ hành\\ kiểm\\ th']", 30000, null, "873b980b-2863-4b3f-9e7d-04603955a632");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bc576f29-800d-4aab-b914-a7fe969a932f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bc576f29-800d-4aab-b914-a7fe969a932f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BaiTậpThựcHanhKiểmThửMonINT31172 item.
            /// </summary>
            [RepositoryItem("873b980b-2863-4b3f-9e7d-04603955a632")]
            public virtual Ranorex.TabPage BaiTậpThựcHanhKiểmThửMonINT31172
            {
                get
                {
                    return _baitậpthựchanhkiểmthửmonint31172Info.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The BaiTậpThựcHanhKiểmThửMonINT31172 item info.
            /// </summary>
            [RepositoryItemInfo("873b980b-2863-4b3f-9e7d-04603955a632")]
            public virtual RepoItemInfo BaiTậpThựcHanhKiểmThửMonINT31172Info
            {
                get
                {
                    return _baitậpthựchanhkiểmthửmonint31172Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
