///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Hoclieu4
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Hoclieu4Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("0212ec58-41fc-4b6f-b87e-26e7edd139c7")]
    public partial class Hoclieu4Repository : RepoGenBaseFolder
    {
        static Hoclieu4Repository instance = new Hoclieu4Repository();
        Hoclieu4RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        Hoclieu4RepositoryFolders.ĐăngNhậpSachMềmAppFolder _đăngnhậpsachmềm;
        Hoclieu4RepositoryFolders.HọcLiệuSachMềmGoogleChromeAppFolder _họcliệusachmềmgooglechrome;

        /// <summary>
        /// Gets the singleton class instance representing the Hoclieu4Repository element repository.
        /// </summary>
        [RepositoryFolder("0212ec58-41fc-4b6f-b87e-26e7edd139c7")]
        public static Hoclieu4Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Hoclieu4Repository() 
            : base("Hoclieu4Repository", "/", null, 0, false, "0212ec58-41fc-4b6f-b87e-26e7edd139c7", ".\\RepositoryImages\\Hoclieu4Repository0212ec58.rximgres")
        {
            _applicationundertest = new Hoclieu4RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _đăngnhậpsachmềm = new Hoclieu4RepositoryFolders.ĐăngNhậpSachMềmAppFolder(this);
            _họcliệusachmềmgooglechrome = new Hoclieu4RepositoryFolders.HọcLiệuSachMềmGoogleChromeAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("0212ec58-41fc-4b6f-b87e-26e7edd139c7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("a88efc18-20b7-464f-b29d-9a7bc0375f78")]
        public virtual Hoclieu4RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The ĐăngNhậpSachMềm folder.
        /// </summary>
        [RepositoryFolder("53395f28-ac3e-4c37-8814-d1d437c14216")]
        public virtual Hoclieu4RepositoryFolders.ĐăngNhậpSachMềmAppFolder ĐăngNhậpSachMềm
        {
            get { return _đăngnhậpsachmềm; }
        }

        /// <summary>
        /// The HọcLiệuSachMềmGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("5f622f20-ab7f-4dbf-9f6e-a4ebc64d1b6d")]
        public virtual Hoclieu4RepositoryFolders.HọcLiệuSachMềmGoogleChromeAppFolder HọcLiệuSachMềmGoogleChrome
        {
            get { return _họcliệusachmềmgooglechrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Hoclieu4RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("a88efc18-20b7-464f-b29d-9a7bc0375f78")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            Hoclieu4RepositoryFolders.ContentBoundFolder _contentbound;
            RepoItemInfo _optiondropdownInfo;
            RepoItemInfo _atagxoabaitậpInfo;
            RepoItemInfo _xacnhậnInfo;
            RepoItemInfo _divtaghọcsinhđalambaikiểmtranayInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='hoclieu.sachmem.vn']", parentFolder, 30000, null, false, "a88efc18-20b7-464f-b29d-9a7bc0375f78", "")
            {
                _contentbound = new Hoclieu4RepositoryFolders.ContentBoundFolder(this);
                _optiondropdownInfo = new RepoItemInfo(this, "OptionDropdown", ".//div[#'scroll-question']//ul/li[3]/div/div[2]/?/?/a[@id='optionDropdown']", 30000, null, "40c6eeeb-b082-47f5-ba73-c8353e9e3881");
                _atagxoabaitậpInfo = new RepoItemInfo(this, "ATagXoaBaiTập", ".//div[#'scroll-question']//ul/li[3]/div/div[2]/span[2]/?/?/a[@innertext=' Xóa bài tập            ']", 30000, null, "2db925f6-8976-45d9-b73f-237894c99fc2");
                _xacnhậnInfo = new RepoItemInfo(this, "XacNhận", "body/div[1]//button[@innertext='Xác nhận']", 30000, null, "bd2e38d7-e6c4-4bb1-8f3d-3b32cbf19bc0");
                _divtaghọcsinhđalambaikiểmtranayInfo = new RepoItemInfo(this, "DivTagHọcSinhĐaLamBaiKiểmTraNay", ".//div[#'toast-container']/?/?/div[@innertext~'^\\ Học\\ sinh\\ đã\\ làm\\ bài\\ kiểm']", 30000, null, "116a907d-ac79-43d2-905e-a9e136493fa0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a88efc18-20b7-464f-b29d-9a7bc0375f78")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a88efc18-20b7-464f-b29d-9a7bc0375f78")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OptionDropdown item.
            /// </summary>
            [RepositoryItem("40c6eeeb-b082-47f5-ba73-c8353e9e3881")]
            public virtual Ranorex.ATag OptionDropdown
            {
                get
                {
                    return _optiondropdownInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The OptionDropdown item info.
            /// </summary>
            [RepositoryItemInfo("40c6eeeb-b082-47f5-ba73-c8353e9e3881")]
            public virtual RepoItemInfo OptionDropdownInfo
            {
                get
                {
                    return _optiondropdownInfo;
                }
            }

            /// <summary>
            /// The ATagXoaBaiTập item.
            /// </summary>
            [RepositoryItem("2db925f6-8976-45d9-b73f-237894c99fc2")]
            public virtual Ranorex.ATag ATagXoaBaiTập
            {
                get
                {
                    return _atagxoabaitậpInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagXoaBaiTập item info.
            /// </summary>
            [RepositoryItemInfo("2db925f6-8976-45d9-b73f-237894c99fc2")]
            public virtual RepoItemInfo ATagXoaBaiTậpInfo
            {
                get
                {
                    return _atagxoabaitậpInfo;
                }
            }

            /// <summary>
            /// The XacNhận item.
            /// </summary>
            [RepositoryItem("bd2e38d7-e6c4-4bb1-8f3d-3b32cbf19bc0")]
            public virtual Ranorex.ButtonTag XacNhận
            {
                get
                {
                    return _xacnhậnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The XacNhận item info.
            /// </summary>
            [RepositoryItemInfo("bd2e38d7-e6c4-4bb1-8f3d-3b32cbf19bc0")]
            public virtual RepoItemInfo XacNhậnInfo
            {
                get
                {
                    return _xacnhậnInfo;
                }
            }

            /// <summary>
            /// The DivTagHọcSinhĐaLamBaiKiểmTraNay item.
            /// </summary>
            [RepositoryItem("116a907d-ac79-43d2-905e-a9e136493fa0")]
            public virtual Ranorex.DivTag DivTagHọcSinhĐaLamBaiKiểmTraNay
            {
                get
                {
                    return _divtaghọcsinhđalambaikiểmtranayInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagHọcSinhĐaLamBaiKiểmTraNay item info.
            /// </summary>
            [RepositoryItemInfo("116a907d-ac79-43d2-905e-a9e136493fa0")]
            public virtual RepoItemInfo DivTagHọcSinhĐaLamBaiKiểmTraNayInfo
            {
                get
                {
                    return _divtaghọcsinhđalambaikiểmtranayInfo;
                }
            }

            /// <summary>
            /// The ContentBound folder.
            /// </summary>
            [RepositoryFolder("72998f57-1fa4-4e86-97b2-097930639763")]
            public virtual Hoclieu4RepositoryFolders.ContentBoundFolder ContentBound
            {
                get { return _contentbound; }
            }
        }

        /// <summary>
        /// The ContentBoundFolder folder.
        /// </summary>
        [RepositoryFolder("72998f57-1fa4-4e86-97b2-097930639763")]
        public partial class ContentBoundFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lớp4Info;
            RepoItemInfo _đăngnhậpInfo;
            RepoItemInfo _lớplớpInfo;
            RepoItemInfo _lớphọccủatoiInfo;

            /// <summary>
            /// Creates a new ContentBound  folder.
            /// </summary>
            public ContentBoundFolder(RepoGenBaseFolder parentFolder) :
                    base("ContentBound", "body/tag[@tagname='app-root']/div[2]", parentFolder, 30000, null, false, "72998f57-1fa4-4e86-97b2-097930639763", "")
            {
                _lớp4Info = new RepoItemInfo(this, "Lớp4", ".//ul/li[7]/div/div[1]/a[@innertext='Lớp 4']", 30000, null, "a64e53fd-2f22-416d-bffc-f276680d11dc");
                _đăngnhậpInfo = new RepoItemInfo(this, "ĐăngNhập", "div//div[@innertext~'^\\ \\ Để\\ sử\\ dụng\\ bạn\\ cần\\ \\ ho']/a[@innertext='Đăng nhập']", 30000, null, "5faa1a46-ffa9-4996-9787-eced2c0ab81d");
                _lớplớpInfo = new RepoItemInfo(this, "LớpLớp", "div//tag[@tagname='app-list-class']/ul[1]/li/div/div[1]/a[@innertext='Lớp lớp']", 30000, null, "dd44077d-d09c-45e4-b65d-b2bd67362e3b");
                _lớphọccủatoiInfo = new RepoItemInfo(this, "LớpHọcCủaToi", "div/div//ul/li[1]//a[@innertext='Lớp học của tôi']", 30000, null, "39a32fa4-8660-40a7-b6fe-ff6debe26226");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("72998f57-1fa4-4e86-97b2-097930639763")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("72998f57-1fa4-4e86-97b2-097930639763")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Lớp4 item.
            /// </summary>
            [RepositoryItem("a64e53fd-2f22-416d-bffc-f276680d11dc")]
            public virtual Ranorex.ATag Lớp4
            {
                get
                {
                    return _lớp4Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Lớp4 item info.
            /// </summary>
            [RepositoryItemInfo("a64e53fd-2f22-416d-bffc-f276680d11dc")]
            public virtual RepoItemInfo Lớp4Info
            {
                get
                {
                    return _lớp4Info;
                }
            }

            /// <summary>
            /// The ĐăngNhập item.
            /// </summary>
            [RepositoryItem("5faa1a46-ffa9-4996-9787-eced2c0ab81d")]
            public virtual Ranorex.ATag ĐăngNhập
            {
                get
                {
                    return _đăngnhậpInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ĐăngNhập item info.
            /// </summary>
            [RepositoryItemInfo("5faa1a46-ffa9-4996-9787-eced2c0ab81d")]
            public virtual RepoItemInfo ĐăngNhậpInfo
            {
                get
                {
                    return _đăngnhậpInfo;
                }
            }

            /// <summary>
            /// The LớpLớp item.
            /// </summary>
            [RepositoryItem("dd44077d-d09c-45e4-b65d-b2bd67362e3b")]
            public virtual Ranorex.ATag LớpLớp
            {
                get
                {
                    return _lớplớpInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LớpLớp item info.
            /// </summary>
            [RepositoryItemInfo("dd44077d-d09c-45e4-b65d-b2bd67362e3b")]
            public virtual RepoItemInfo LớpLớpInfo
            {
                get
                {
                    return _lớplớpInfo;
                }
            }

            /// <summary>
            /// The LớpHọcCủaToi item.
            /// </summary>
            [RepositoryItem("39a32fa4-8660-40a7-b6fe-ff6debe26226")]
            public virtual Ranorex.ATag LớpHọcCủaToi
            {
                get
                {
                    return _lớphọccủatoiInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LớpHọcCủaToi item info.
            /// </summary>
            [RepositoryItemInfo("39a32fa4-8660-40a7-b6fe-ff6debe26226")]
            public virtual RepoItemInfo LớpHọcCủaToiInfo
            {
                get
                {
                    return _lớphọccủatoiInfo;
                }
            }
        }

        /// <summary>
        /// The ĐăngNhậpSachMềmAppFolder folder.
        /// </summary>
        [RepositoryFolder("53395f28-ac3e-4c37-8814-d1d437c14216")]
        public partial class ĐăngNhậpSachMềmAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _commitInfo;

            /// <summary>
            /// Creates a new ĐăngNhậpSachMềm  folder.
            /// </summary>
            public ĐăngNhậpSachMềmAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ĐăngNhậpSachMềm", "/dom[@domain='accounts.sachmem.vn']", parentFolder, 30000, null, false, "53395f28-ac3e-4c37-8814-d1d437c14216", "")
            {
                _commitInfo = new RepoItemInfo(this, "Commit", ".//form[#'new_user']/?/?/input[@name='commit']", 30000, null, "06473092-26d2-431f-a77c-e90fc355418f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("53395f28-ac3e-4c37-8814-d1d437c14216")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("53395f28-ac3e-4c37-8814-d1d437c14216")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Commit item.
            /// </summary>
            [RepositoryItem("06473092-26d2-431f-a77c-e90fc355418f")]
            public virtual Ranorex.InputTag Commit
            {
                get
                {
                    return _commitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Commit item info.
            /// </summary>
            [RepositoryItemInfo("06473092-26d2-431f-a77c-e90fc355418f")]
            public virtual RepoItemInfo CommitInfo
            {
                get
                {
                    return _commitInfo;
                }
            }
        }

        /// <summary>
        /// The HọcLiệuSachMềmGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("5f622f20-ab7f-4dbf-9f6e-a4ebc64d1b6d")]
        public partial class HọcLiệuSachMềmGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _backInfo;

            /// <summary>
            /// Creates a new HọcLiệuSachMềmGoogleChrome  folder.
            /// </summary>
            public HọcLiệuSachMềmGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HọcLiệuSachMềmGoogleChrome", "/form[@title~'^Học\\ liệu\\ -\\ Sách\\ Mềm\\ -\\ Goo']", parentFolder, 30000, null, true, "5f622f20-ab7f-4dbf-9f6e-a4ebc64d1b6d", "")
            {
                _backInfo = new RepoItemInfo(this, "Back", "container[@accessiblename~'^Học\\ liệu\\ -\\ Sách\\ Mềm\\ -\\ Goo']/container[@accessiblename='Google Chrome']//button[@accessiblename='Back']", 30000, null, "cf0ac21a-06f5-42eb-b3a3-fc44021290cc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5f622f20-ab7f-4dbf-9f6e-a4ebc64d1b6d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5f622f20-ab7f-4dbf-9f6e-a4ebc64d1b6d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Back item.
            /// </summary>
            [RepositoryItem("cf0ac21a-06f5-42eb-b3a3-fc44021290cc")]
            public virtual Ranorex.Button Back
            {
                get
                {
                    return _backInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Back item info.
            /// </summary>
            [RepositoryItemInfo("cf0ac21a-06f5-42eb-b3a3-fc44021290cc")]
            public virtual RepoItemInfo BackInfo
            {
                get
                {
                    return _backInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
