///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Hoclieu8
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Hoclieu8Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("01f0b4bf-ec1b-49ae-8a5a-8db05edd402a")]
    public partial class Hoclieu8Repository : RepoGenBaseFolder
    {
        static Hoclieu8Repository instance = new Hoclieu8Repository();
        Hoclieu8RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        Hoclieu8RepositoryFolders.ĐăngNhậpSachMềmAppFolder _đăngnhậpsachmềm;

        /// <summary>
        /// Gets the singleton class instance representing the Hoclieu8Repository element repository.
        /// </summary>
        [RepositoryFolder("01f0b4bf-ec1b-49ae-8a5a-8db05edd402a")]
        public static Hoclieu8Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Hoclieu8Repository() 
            : base("Hoclieu8Repository", "/", null, 0, false, "01f0b4bf-ec1b-49ae-8a5a-8db05edd402a", ".\\RepositoryImages\\Hoclieu8Repository01f0b4bf.rximgres")
        {
            _applicationundertest = new Hoclieu8RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _đăngnhậpsachmềm = new Hoclieu8RepositoryFolders.ĐăngNhậpSachMềmAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("01f0b4bf-ec1b-49ae-8a5a-8db05edd402a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("4feb79df-cf82-44a9-b8e7-f5860159c767")]
        public virtual Hoclieu8RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The ĐăngNhậpSachMềm folder.
        /// </summary>
        [RepositoryFolder("1d5052d6-f81f-48a3-bc39-f1ad8eb99ed3")]
        public virtual Hoclieu8RepositoryFolders.ĐăngNhậpSachMềmAppFolder ĐăngNhậpSachMềm
        {
            get { return _đăngnhậpsachmềm; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Hoclieu8RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("4feb79df-cf82-44a9-b8e7-f5860159c767")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            Hoclieu8RepositoryFolders.ContentBoundFolder _contentbound;
            RepoItemInfo _submitInfo;
            RepoItemInfo _trườngnaykhongđượcđểtrốngInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='hoclieu.sachmem.vn']", parentFolder, 30000, null, false, "4feb79df-cf82-44a9-b8e7-f5860159c767", "")
            {
                _contentbound = new Hoclieu8RepositoryFolders.ContentBoundFolder(this);
                _submitInfo = new RepoItemInfo(this, "Submit", ".//div[#'createAssignmentModal']//form[@action='https://hoclieu.sachmem.vn/question_set/5a4b18b248150cd8b90656fe/5a4b18b248150cd8b9065701/preview']/?/?/input[@type='submit']", 30000, null, "1b170c42-771c-4a68-af17-a22d6a9846fa");
                _trườngnaykhongđượcđểtrốngInfo = new RepoItemInfo(this, "TrườngNayKhongĐượcĐểTrống", ".//div[#'createAssignmentModal']//form[@action='https://hoclieu.sachmem.vn/question_set/5a4b18b248150cd8b90656fe/5a4b18b248150cd8b9065701/preview']/div[1]/div[3]/div[@innertext~'^Trường\\ này\\ không\\ được\\ để\\ ']", 30000, null, "5704495c-6b31-4ba3-9fdb-b58d767c96a4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4feb79df-cf82-44a9-b8e7-f5860159c767")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4feb79df-cf82-44a9-b8e7-f5860159c767")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("1b170c42-771c-4a68-af17-a22d6a9846fa")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("1b170c42-771c-4a68-af17-a22d6a9846fa")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The TrườngNayKhongĐượcĐểTrống item.
            /// </summary>
            [RepositoryItem("5704495c-6b31-4ba3-9fdb-b58d767c96a4")]
            public virtual Ranorex.DivTag TrườngNayKhongĐượcĐểTrống
            {
                get
                {
                    return _trườngnaykhongđượcđểtrốngInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The TrườngNayKhongĐượcĐểTrống item info.
            /// </summary>
            [RepositoryItemInfo("5704495c-6b31-4ba3-9fdb-b58d767c96a4")]
            public virtual RepoItemInfo TrườngNayKhongĐượcĐểTrốngInfo
            {
                get
                {
                    return _trườngnaykhongđượcđểtrốngInfo;
                }
            }

            /// <summary>
            /// The ContentBound folder.
            /// </summary>
            [RepositoryFolder("3421d8da-a498-4e8a-81f7-9c4f269c400c")]
            public virtual Hoclieu8RepositoryFolders.ContentBoundFolder ContentBound
            {
                get { return _contentbound; }
            }
        }

        /// <summary>
        /// The ContentBoundFolder folder.
        /// </summary>
        [RepositoryFolder("3421d8da-a498-4e8a-81f7-9c4f269c400c")]
        public partial class ContentBoundFolder : RepoGenBaseFolder
        {
            RepoItemInfo _giaobaitậpInfo;
            RepoItemInfo _luyệntậptiếnganh4tập1Info;
            RepoItemInfo _lớp4Info;
            RepoItemInfo _đăngnhậpInfo;

            /// <summary>
            /// Creates a new ContentBound  folder.
            /// </summary>
            public ContentBoundFolder(RepoGenBaseFolder parentFolder) :
                    base("ContentBound", "body/tag[@tagname='app-root']/div[2]", parentFolder, 30000, null, false, "3421d8da-a498-4e8a-81f7-9c4f269c400c", "")
            {
                _giaobaitậpInfo = new RepoItemInfo(this, "GiaoBaiTập", ".//tag[@tagname='question']/div/div[2]/div/?/?/tag[@tagname='app-preview-list-question']/div/div[1]/div[1]/div[2]/a[@href='javascript:void(0)']/span[@innertext='Giao bài tập']", 30000, null, "e9fce7ca-c809-4967-addf-485892026bd5");
                _luyệntậptiếnganh4tập1Info = new RepoItemInfo(this, "LuyệnTậpTiếngAnh4Tập1", ".//ul/li[5]/div/div[1]/a[@innertext~'^Luyện\\ tập\\ Tiếng\\ Anh\\ 4\\ Tập']", 30000, null, "011825a3-73e6-4099-9f22-964a48e2c338");
                _lớp4Info = new RepoItemInfo(this, "Lớp4", ".//ul/li[7]/div/div[1]/a[@innertext='Lớp 4']", 30000, null, "0f88f1a4-cca5-44c8-9196-451a5bcacc21");
                _đăngnhậpInfo = new RepoItemInfo(this, "ĐăngNhập", "div//div[@innertext~'^\\ \\ Để\\ sử\\ dụng\\ bạn\\ cần\\ \\ ho']/a[@innertext='Đăng nhập']", 30000, null, "16a9c8fa-c09a-4c92-840e-c50c5b0393b1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3421d8da-a498-4e8a-81f7-9c4f269c400c")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3421d8da-a498-4e8a-81f7-9c4f269c400c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GiaoBaiTập item.
            /// </summary>
            [RepositoryItem("e9fce7ca-c809-4967-addf-485892026bd5")]
            public virtual Ranorex.SpanTag GiaoBaiTập
            {
                get
                {
                    return _giaobaitậpInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GiaoBaiTập item info.
            /// </summary>
            [RepositoryItemInfo("e9fce7ca-c809-4967-addf-485892026bd5")]
            public virtual RepoItemInfo GiaoBaiTậpInfo
            {
                get
                {
                    return _giaobaitậpInfo;
                }
            }

            /// <summary>
            /// The LuyệnTậpTiếngAnh4Tập1 item.
            /// </summary>
            [RepositoryItem("011825a3-73e6-4099-9f22-964a48e2c338")]
            public virtual Ranorex.ATag LuyệnTậpTiếngAnh4Tập1
            {
                get
                {
                    return _luyệntậptiếnganh4tập1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LuyệnTậpTiếngAnh4Tập1 item info.
            /// </summary>
            [RepositoryItemInfo("011825a3-73e6-4099-9f22-964a48e2c338")]
            public virtual RepoItemInfo LuyệnTậpTiếngAnh4Tập1Info
            {
                get
                {
                    return _luyệntậptiếnganh4tập1Info;
                }
            }

            /// <summary>
            /// The Lớp4 item.
            /// </summary>
            [RepositoryItem("0f88f1a4-cca5-44c8-9196-451a5bcacc21")]
            public virtual Ranorex.ATag Lớp4
            {
                get
                {
                    return _lớp4Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Lớp4 item info.
            /// </summary>
            [RepositoryItemInfo("0f88f1a4-cca5-44c8-9196-451a5bcacc21")]
            public virtual RepoItemInfo Lớp4Info
            {
                get
                {
                    return _lớp4Info;
                }
            }

            /// <summary>
            /// The ĐăngNhập item.
            /// </summary>
            [RepositoryItem("16a9c8fa-c09a-4c92-840e-c50c5b0393b1")]
            public virtual Ranorex.ATag ĐăngNhập
            {
                get
                {
                    return _đăngnhậpInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ĐăngNhập item info.
            /// </summary>
            [RepositoryItemInfo("16a9c8fa-c09a-4c92-840e-c50c5b0393b1")]
            public virtual RepoItemInfo ĐăngNhậpInfo
            {
                get
                {
                    return _đăngnhậpInfo;
                }
            }
        }

        /// <summary>
        /// The ĐăngNhậpSachMềmAppFolder folder.
        /// </summary>
        [RepositoryFolder("1d5052d6-f81f-48a3-bc39-f1ad8eb99ed3")]
        public partial class ĐăngNhậpSachMềmAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _commitInfo;

            /// <summary>
            /// Creates a new ĐăngNhậpSachMềm  folder.
            /// </summary>
            public ĐăngNhậpSachMềmAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ĐăngNhậpSachMềm", "/dom[@domain='accounts.sachmem.vn']", parentFolder, 30000, null, false, "1d5052d6-f81f-48a3-bc39-f1ad8eb99ed3", "")
            {
                _commitInfo = new RepoItemInfo(this, "Commit", ".//form[#'new_user']/?/?/input[@name='commit']", 30000, null, "e108ab2d-a6de-418c-a1e9-a9a685f77583");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1d5052d6-f81f-48a3-bc39-f1ad8eb99ed3")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1d5052d6-f81f-48a3-bc39-f1ad8eb99ed3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Commit item.
            /// </summary>
            [RepositoryItem("e108ab2d-a6de-418c-a1e9-a9a685f77583")]
            public virtual Ranorex.InputTag Commit
            {
                get
                {
                    return _commitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Commit item info.
            /// </summary>
            [RepositoryItemInfo("e108ab2d-a6de-418c-a1e9-a9a685f77583")]
            public virtual RepoItemInfo CommitInfo
            {
                get
                {
                    return _commitInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
