///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Hoclieu2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Hoclieu2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("d3f47b8e-d74e-447d-a7a3-99b77805958a")]
    public partial class Hoclieu2Repository : RepoGenBaseFolder
    {
        static Hoclieu2Repository instance = new Hoclieu2Repository();
        Hoclieu2RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        Hoclieu2RepositoryFolders.ĐăngNhậpSachMềmAppFolder _đăngnhậpsachmềm;

        /// <summary>
        /// Gets the singleton class instance representing the Hoclieu2Repository element repository.
        /// </summary>
        [RepositoryFolder("d3f47b8e-d74e-447d-a7a3-99b77805958a")]
        public static Hoclieu2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Hoclieu2Repository() 
            : base("Hoclieu2Repository", "/", null, 0, false, "d3f47b8e-d74e-447d-a7a3-99b77805958a", ".\\RepositoryImages\\Hoclieu2Repositoryd3f47b8e.rximgres")
        {
            _applicationundertest = new Hoclieu2RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _đăngnhậpsachmềm = new Hoclieu2RepositoryFolders.ĐăngNhậpSachMềmAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d3f47b8e-d74e-447d-a7a3-99b77805958a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("1872fca6-d55b-4f41-ad54-137d047a6bd4")]
        public virtual Hoclieu2RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The ĐăngNhậpSachMềm folder.
        /// </summary>
        [RepositoryFolder("60706f0c-c493-457a-8d5c-1d34738aa23c")]
        public virtual Hoclieu2RepositoryFolders.ĐăngNhậpSachMềmAppFolder ĐăngNhậpSachMềm
        {
            get { return _đăngnhậpsachmềm; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Hoclieu2RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("1872fca6-d55b-4f41-ad54-137d047a6bd4")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            Hoclieu2RepositoryFolders.HttpsHoclieuSachmemVnQuestionSetFolder _httpshoclieusachmemvnquestionset;
            Hoclieu2RepositoryFolders.ContentBoundFolder _contentbound;
            RepoItemInfo _divtagsốlầnlamlạiphảilớnhơnhoặcInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='hoclieu.sachmem.vn']", parentFolder, 30000, null, false, "1872fca6-d55b-4f41-ad54-137d047a6bd4", "")
            {
                _httpshoclieusachmemvnquestionset = new Hoclieu2RepositoryFolders.HttpsHoclieuSachmemVnQuestionSetFolder(this);
                _contentbound = new Hoclieu2RepositoryFolders.ContentBoundFolder(this);
                _divtagsốlầnlamlạiphảilớnhơnhoặcInfo = new RepoItemInfo(this, "DivTagSốLầnLamLạiPhảiLớnHơnHoặc", ".//div[#'toast-container']/?/?/div[@innertext~'^\\ Số\\ lần\\ làm\\ lại\\ phải\\ lớn\\ ']", 30000, null, "193cb6cc-b65a-4408-ae53-eaf7d9fdba66");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1872fca6-d55b-4f41-ad54-137d047a6bd4")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1872fca6-d55b-4f41-ad54-137d047a6bd4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DivTagSốLầnLamLạiPhảiLớnHơnHoặc item.
            /// </summary>
            [RepositoryItem("193cb6cc-b65a-4408-ae53-eaf7d9fdba66")]
            public virtual Ranorex.DivTag DivTagSốLầnLamLạiPhảiLớnHơnHoặc
            {
                get
                {
                    return _divtagsốlầnlamlạiphảilớnhơnhoặcInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTagSốLầnLamLạiPhảiLớnHơnHoặc item info.
            /// </summary>
            [RepositoryItemInfo("193cb6cc-b65a-4408-ae53-eaf7d9fdba66")]
            public virtual RepoItemInfo DivTagSốLầnLamLạiPhảiLớnHơnHoặcInfo
            {
                get
                {
                    return _divtagsốlầnlamlạiphảilớnhơnhoặcInfo;
                }
            }

            /// <summary>
            /// The HttpsHoclieuSachmemVnQuestionSet folder.
            /// </summary>
            [RepositoryFolder("54d6d301-ed52-4c84-b0f9-9464e48e1201")]
            public virtual Hoclieu2RepositoryFolders.HttpsHoclieuSachmemVnQuestionSetFolder HttpsHoclieuSachmemVnQuestionSet
            {
                get { return _httpshoclieusachmemvnquestionset; }
            }

            /// <summary>
            /// The ContentBound folder.
            /// </summary>
            [RepositoryFolder("e248a2f9-83e2-4d70-a8f9-6aadeab89527")]
            public virtual Hoclieu2RepositoryFolders.ContentBoundFolder ContentBound
            {
                get { return _contentbound; }
            }
        }

        /// <summary>
        /// The HttpsHoclieuSachmemVnQuestionSetFolder folder.
        /// </summary>
        [RepositoryFolder("54d6d301-ed52-4c84-b0f9-9464e48e1201")]
        public partial class HttpsHoclieuSachmemVnQuestionSetFolder : RepoGenBaseFolder
        {
            RepoItemInfo _submitInfo;
            RepoItemInfo _ngoptionngoptionmarkedInfo;
            RepoItemInfo _nginputInfo;
            RepoItemInfo _numberInfo;

            /// <summary>
            /// Creates a new HttpsHoclieuSachmemVnQuestionSet  folder.
            /// </summary>
            public HttpsHoclieuSachmemVnQuestionSetFolder(RepoGenBaseFolder parentFolder) :
                    base("HttpsHoclieuSachmemVnQuestionSet", ".//div[#'createAssignmentModal']//form[@action='https://hoclieu.sachmem.vn/question_set/5a4b18b248150cd8b90656fe/5a4b18b248150cd8b9065701/preview']", parentFolder, 30000, null, false, "54d6d301-ed52-4c84-b0f9-9464e48e1201", "")
            {
                _submitInfo = new RepoItemInfo(this, "Submit", "?/?/input[@type='submit']", 30000, null, "5ddaa974-bb71-4795-aa15-b8ff4510808e");
                _ngoptionngoptionmarkedInfo = new RepoItemInfo(this, "NgOptionNgOptionMarked", "div[1]/div[3]/?/?/tag[@tagname='ng-dropdown-panel']/div/div[2]/div", 30000, null, "17810c45-0c73-47f7-88a8-3d79fbe6f7d6");
                _nginputInfo = new RepoItemInfo(this, "NgInput", "div[1]/div[3]/tag[@tagname='ng-select']/div/div/div[2]", 30000, null, "ba0afcfe-cebe-4493-8bb2-b71715d263a1");
                _numberInfo = new RepoItemInfo(this, "Number", "div[1]/div[7]/input[@type='number']", 30000, null, "f83da695-3f16-4894-931f-6c7e8f1855d7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("54d6d301-ed52-4c84-b0f9-9464e48e1201")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("54d6d301-ed52-4c84-b0f9-9464e48e1201")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("5ddaa974-bb71-4795-aa15-b8ff4510808e")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("5ddaa974-bb71-4795-aa15-b8ff4510808e")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The NgOptionNgOptionMarked item.
            /// </summary>
            [RepositoryItem("17810c45-0c73-47f7-88a8-3d79fbe6f7d6")]
            public virtual Ranorex.DivTag NgOptionNgOptionMarked
            {
                get
                {
                    return _ngoptionngoptionmarkedInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The NgOptionNgOptionMarked item info.
            /// </summary>
            [RepositoryItemInfo("17810c45-0c73-47f7-88a8-3d79fbe6f7d6")]
            public virtual RepoItemInfo NgOptionNgOptionMarkedInfo
            {
                get
                {
                    return _ngoptionngoptionmarkedInfo;
                }
            }

            /// <summary>
            /// The NgInput item.
            /// </summary>
            [RepositoryItem("ba0afcfe-cebe-4493-8bb2-b71715d263a1")]
            public virtual Ranorex.DivTag NgInput
            {
                get
                {
                    return _nginputInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The NgInput item info.
            /// </summary>
            [RepositoryItemInfo("ba0afcfe-cebe-4493-8bb2-b71715d263a1")]
            public virtual RepoItemInfo NgInputInfo
            {
                get
                {
                    return _nginputInfo;
                }
            }

            /// <summary>
            /// The Number item.
            /// </summary>
            [RepositoryItem("f83da695-3f16-4894-931f-6c7e8f1855d7")]
            public virtual Ranorex.InputTag Number
            {
                get
                {
                    return _numberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Number item info.
            /// </summary>
            [RepositoryItemInfo("f83da695-3f16-4894-931f-6c7e8f1855d7")]
            public virtual RepoItemInfo NumberInfo
            {
                get
                {
                    return _numberInfo;
                }
            }
        }

        /// <summary>
        /// The ContentBoundFolder folder.
        /// </summary>
        [RepositoryFolder("e248a2f9-83e2-4d70-a8f9-6aadeab89527")]
        public partial class ContentBoundFolder : RepoGenBaseFolder
        {
            RepoItemInfo _giaobaitậpInfo;
            RepoItemInfo _lớp4Info;
            RepoItemInfo _luyệntậptiếnganh4tập1Info;
            RepoItemInfo _đăngnhậpInfo;

            /// <summary>
            /// Creates a new ContentBound  folder.
            /// </summary>
            public ContentBoundFolder(RepoGenBaseFolder parentFolder) :
                    base("ContentBound", "body/tag[@tagname='app-root']/div[2]", parentFolder, 30000, null, false, "e248a2f9-83e2-4d70-a8f9-6aadeab89527", "")
            {
                _giaobaitậpInfo = new RepoItemInfo(this, "GiaoBaiTập", ".//tag[@tagname='question']/div/div[2]/div/?/?/tag[@tagname='app-preview-list-question']/div/div[1]/div[1]/div[2]/a[@href='javascript:void(0)']/span[@innertext='Giao bài tập']", 30000, null, "e1ac19ff-7779-4e32-8470-04a2be5caa45");
                _lớp4Info = new RepoItemInfo(this, "Lớp4", ".//ul/li[7]/div/div[1]/a[@innertext='Lớp 4']", 30000, null, "10eb9b10-1099-4faf-aec9-55f01bbf8f19");
                _luyệntậptiếnganh4tập1Info = new RepoItemInfo(this, "LuyệnTậpTiếngAnh4Tập1", ".//ul/li[7]/div/div[1]/a[@innertext~'^Luyện\\ tập\\ Tiếng\\ Anh\\ 4\\ Tập']", 30000, null, "9c3ecfa2-fde9-4c75-aa54-8df36235262c");
                _đăngnhậpInfo = new RepoItemInfo(this, "ĐăngNhập", "div//div[@innertext~'^\\ \\ Để\\ sử\\ dụng\\ bạn\\ cần\\ \\ ho']/a[@innertext='Đăng nhập']", 30000, null, "bbea3877-3e6e-4735-8d51-dc92348e3d4f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e248a2f9-83e2-4d70-a8f9-6aadeab89527")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e248a2f9-83e2-4d70-a8f9-6aadeab89527")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GiaoBaiTập item.
            /// </summary>
            [RepositoryItem("e1ac19ff-7779-4e32-8470-04a2be5caa45")]
            public virtual Ranorex.SpanTag GiaoBaiTập
            {
                get
                {
                    return _giaobaitậpInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GiaoBaiTập item info.
            /// </summary>
            [RepositoryItemInfo("e1ac19ff-7779-4e32-8470-04a2be5caa45")]
            public virtual RepoItemInfo GiaoBaiTậpInfo
            {
                get
                {
                    return _giaobaitậpInfo;
                }
            }

            /// <summary>
            /// The Lớp4 item.
            /// </summary>
            [RepositoryItem("10eb9b10-1099-4faf-aec9-55f01bbf8f19")]
            public virtual Ranorex.ATag Lớp4
            {
                get
                {
                    return _lớp4Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Lớp4 item info.
            /// </summary>
            [RepositoryItemInfo("10eb9b10-1099-4faf-aec9-55f01bbf8f19")]
            public virtual RepoItemInfo Lớp4Info
            {
                get
                {
                    return _lớp4Info;
                }
            }

            /// <summary>
            /// The LuyệnTậpTiếngAnh4Tập1 item.
            /// </summary>
            [RepositoryItem("9c3ecfa2-fde9-4c75-aa54-8df36235262c")]
            public virtual Ranorex.ATag LuyệnTậpTiếngAnh4Tập1
            {
                get
                {
                    return _luyệntậptiếnganh4tập1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LuyệnTậpTiếngAnh4Tập1 item info.
            /// </summary>
            [RepositoryItemInfo("9c3ecfa2-fde9-4c75-aa54-8df36235262c")]
            public virtual RepoItemInfo LuyệnTậpTiếngAnh4Tập1Info
            {
                get
                {
                    return _luyệntậptiếnganh4tập1Info;
                }
            }

            /// <summary>
            /// The ĐăngNhập item.
            /// </summary>
            [RepositoryItem("bbea3877-3e6e-4735-8d51-dc92348e3d4f")]
            public virtual Ranorex.ATag ĐăngNhập
            {
                get
                {
                    return _đăngnhậpInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ĐăngNhập item info.
            /// </summary>
            [RepositoryItemInfo("bbea3877-3e6e-4735-8d51-dc92348e3d4f")]
            public virtual RepoItemInfo ĐăngNhậpInfo
            {
                get
                {
                    return _đăngnhậpInfo;
                }
            }
        }

        /// <summary>
        /// The ĐăngNhậpSachMềmAppFolder folder.
        /// </summary>
        [RepositoryFolder("60706f0c-c493-457a-8d5c-1d34738aa23c")]
        public partial class ĐăngNhậpSachMềmAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _commitInfo;

            /// <summary>
            /// Creates a new ĐăngNhậpSachMềm  folder.
            /// </summary>
            public ĐăngNhậpSachMềmAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ĐăngNhậpSachMềm", "/dom[@domain='accounts.sachmem.vn']", parentFolder, 30000, null, false, "60706f0c-c493-457a-8d5c-1d34738aa23c", "")
            {
                _commitInfo = new RepoItemInfo(this, "Commit", ".//form[#'new_user']/?/?/input[@name='commit']", 30000, null, "9c6dd4a5-e9ae-46a6-b4d5-74de929827fe");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("60706f0c-c493-457a-8d5c-1d34738aa23c")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("60706f0c-c493-457a-8d5c-1d34738aa23c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Commit item.
            /// </summary>
            [RepositoryItem("9c6dd4a5-e9ae-46a6-b4d5-74de929827fe")]
            public virtual Ranorex.InputTag Commit
            {
                get
                {
                    return _commitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Commit item info.
            /// </summary>
            [RepositoryItemInfo("9c6dd4a5-e9ae-46a6-b4d5-74de929827fe")]
            public virtual RepoItemInfo CommitInfo
            {
                get
                {
                    return _commitInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
